# 异常处理

## 1、基础了解

​	异常也就是非正常情况，正常是自上向下顺序执行，异常就是半途遇到了错误造成了意外终止

```python
try:  # 尝试
    pass  # 代码块，也就是需要检查错误保护的代码
except 异常类型:  # 捕获对应错误
    pass  # 发生异常处理异常的代码
```

​	具体基础使用代码如下：

```python
# coding:UTF-8

if __name__ == '__main__':
    try:
        a = 1/0
    except Exception as e:
        print(f'0不能作为除数哦,{e}')
```

![img](https://raw.githubusercontent.com/TuiYinMJ/Python-img/master/Python-img/exception.jpeg)

​	如上，所有的异常类都继承于一个BaseException和Exception的基类，我们可以通过捕获基类获取异常，也可以通过捕获具体的类型，比如ZeroDivisionError，as是起一个别名，可以通过输出e来输出具体的错误信息

​	也就是若我们知道可能具体会出现什么异常的话，就可以捕获具体的异常，若我们不知道会发生什么错误，可以用Exception来捕获

​	**若具体异常和通用异常搭配使用，通用异常要放到最后，否则匹配通用异常后就不再向后执行**

```python
# coding:UTF-8

if __name__ == '__main__':
    try:
        a = 1/'855'
    except ZeroDivisionError:
        print('ZeroDivisionError')
    except Exception as e:
        print(e)
```

​	如上，可以有多个Except同时捕获

```python
# coding:UTF-8

if __name__ == '__main__':
    try:
        a = 1/'855'
    except (ZeroDivisionError,Exception) as e:
        print(f'Error:{e}')
```

​	也可以如上，自左向右依次继承



## 2、常见异常类型

- Exception：通用异常基类
- ZeroDivisionError：不能整除0
- AttributeError：对象没有这属性
- IOError：输入输出失败
- IndexError：无当前索引
- KeyError：没有这个键
- NameError：没有这个变量，对象未初始化
- SyntaxError：Python语法错误
- SystemError：解释器系统错误
- ValueError：传入参数错误
- TypeError：类型错误
- ImportError：无法导入模块
- FileExistsError：文件已经存在
- FileNotFoundError：未找到文件
- MemoryError：内存不足
- OverflowError：运算超范围



## 3、finally

​	finally不管异常与否，都会执行

```python
# coding:UTF-8

if __name__ == '__main__':
    try:
        1/0
    except Exception as e:
        print(e)
    finally:
        print('finally')

```

​	如上，不管是否异常，都会执行finally



## 4、自定义异常

​	有时候自定义异常并无法满足我们开发的全部需求，所以我们也可以自定义异常

​	可以通过 raise 语句抛出异常

```python
# coding:UTF-8

class MyException(Exception):
    def __init__(self, message):
        super().__init__(message)
        self.message = message  # 异常的描述信息

    def __str__(self):
        return f"{self.__class__.__name__}: {self.message}"


def testE(num):
    if num < 0:
        raise MyException("不能小于0")  # 若num<0则通过raise抛出异常
    return num * 2


if __name__ == '__main__':
    try:
        testE(-5)
    except MyException as e:
        print(e)

```



## 5、断言

​	assert，判断一个表达式，为False的时候触发异常

​	用法：

```python
assert expression,message
```

​	expression是表达式，用于判断，message是错误显示的信息

```python
# coding:UTF-8
def add(x, y):
    assert(x >= 0 and y >= 0), "参数不能为负数"
    return x + y

if __name__ == '__main__':
    add(-1,5)
```

​	如上，若一个函数不需要负数为参数，就可以用断言更简洁的抛出错误

​	当x和y有一个为负数，则抛出message，否则返回两者之和



